services:
  - type: web
    name: mini-crm-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false 